version: "3.8"

x-app: &x-app
  build:
    dockerfile: Dockerfile
    context: .
    target: production
  depends_on:
    - postgres
  environment:
    IS_COMPOSE: "true"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: zeplytest
      POSTGRES_DB: zeplytest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql

  app:
    <<: *x-app
    ports:
      - "8000:8000"

  migrate:
    <<: *x-app
    command: python -m manage migrate

  development:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/code
    depends_on:
      - postgres
    environment:
      IS_COMPOSE: "true"
    ports:
      - "8000:8000"
