# Generated by Django 4.1.7 on 2023-03-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                (
                    "network",
                    models.TextField(choices=[("BTC", "BTC"), ("ETH", "ETH"), ("XRP", "XRP")]),
                ),
                (
                    "wallet",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="wallets.wallet"),
                ),
            ],
            options={
                "unique_together": {("network", "wallet")},
            },
        ),
    ]
