# Generated by Django 4.1.7 on 2023-03-12 16:54

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", django_cryptography.fields.encrypt(models.TextField())),
                (
                    "sequence",
                    django_cryptography.fields.encrypt(models.DecimalField(decimal_places=0, max_digits=10)),
                ),
                ("public_key", models.TextField()),
                ("private_key", django_cryptography.fields.encrypt(models.TextField())),
            ],
        ),
    ]
